FROM butter/python:3.6.0

RUN pip install --no-cache-dir \
    analytics-python==1.2.6 \
    attrs==16.3.0 \
    bcrypt==3.1.2 \
    Celery==4.0.2 \
    colorlog==2.10.0 \
    Flask-API==0.6.9 \
    Flask==0.12 \
    future==0.16.0 \
    ipdb==0.10.0 \
    ipython==5.1.0 \
    psycopg2==2.6.2 \
    pymongo==3.4.0 \
    python-dateutil==2.6.0 \
    pytz==2016.10 \
    redis==2.10.5 \
    requests==2.12.5 \
    uwsgi==2.0.14

CMD ["python3"]
