FROM butter/python:2.7.13
LABEL maintainer="Butter.ai <dev@butter.ai>"

RUN pip install --no-cache-dir \
    analytics-python==1.2.9 \
    attrs==17.4.0 \
    bcrypt==3.1.4 \
    beautifulsoup4==4.6.0 \
    Celery==4.1.0 \
    colorlog==3.1.2 \
    evernote==1.25.3 \
    Flask-API==1.0 \
    Flask==0.12.2 \
    future==0.16.0 \
    google-api-python-client==1.6.5 \
    ipdb==0.11 \
    ipython==5.5.0 \
    jsonpickle==0.9.6 \
    logstash_formatter==0.5.17 \
    oauth2client==4.1.2 \
    pika==0.11.2 \
    psycopg2==2.7.4 \
    PyJWT==1.6.0 \
    pymongo==3.6.1 \
    python-dateutil==2.6.1 \
    pytz==2018.3 \
    raven==6.5.0 \
    redis==2.10.6 \
    requests==2.18.4 \
    slackclient==1.1.2 \
    uwsgi==2.0.15 \
    web-pdb==1.3.4
